### ISSUE TITLE
Entita s měsíční spotřebou/výrobou

### ISSUE THREAD

**Issue by otava5** [ondrejvysek/HomeAssistant-EGD-PowerData#2]
Dobrý den,
šla by dodělat entita s měsíční spotřebou a výrobou např. aktualizace k 1 dni v měsíci za předchozí měsíc?

Děkuji

**Comment by ondrejvysek** [comment]
Dobrý den, šlo. nicméně pokud bude dost dat v HA, je lepší udělat statistický senzor ze surových dat. mohlo by to vypadat nějak takto:
```
sensor:
  - platform: statistics
    name: Daily Sensor Statistics
    entity_id: sensor.egddistribuce_00000EAN00000_1_icc1
    sampling_size: 30
    max_age:
      days: 30
```
pak zajistit reset sensozu na konci měsíce.

potažmo by šlo agregace řešit v nějaké lovelace, třeba apex, která udělá sum za období.

nechám to tu otevřené jako vylepšení, jak bude hotový základ a budou nasbíraná data, začneme řešit agregace / vizualizace.
